version: "3.7"

services:
  app:
    build: ./docker
    image: rabbialrabbi/ticketapp
    ports:
      - "8080:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: rabbialrabbi
      MYSQL_PASSWORD: PassW@rd123

volumes:
  mysql-data:
